"""initial schema — Section 3 of the Cadence spec

Revision ID: 0001
Revises:
Create Date: 2026-05-16

Hand-authored (not autogenerated) so the schema can be created without first standing
up Postgres. Mirrors app.models exactly; keep them in sync on future changes.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TASK_STATUSES = ("pending", "scheduled", "in_progress", "done", "decayed")
PROJECT_STATUSES = ("active", "paused", "done", "archived")
PRESENCE_STATUSES = ("focusing", "idle", "offline")
USER_ROLES = ("cofounder", "team", "contractor")


def _in_clause(col: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{v}'" for v in values)
    return f"{col} IN ({quoted})"


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("role", sa.String(32), nullable=False, server_default="cofounder"),
        sa.Column("capacity_score", sa.Float, nullable=False, server_default="50.0"),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="UTC"),
        sa.Column("push_token", sa.String(255)),
        sa.Column("energy_curve", sa.JSON),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(_in_clause("role", USER_ROLES), name="ck_users_role"),
        sa.CheckConstraint("capacity_score >= 0 AND capacity_score <= 100", name="ck_users_capacity_range"),
    )

    op.create_table(
        "projects",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("north_star", sa.Text),
        sa.Column("status", sa.String(32), nullable=False, server_default="active"),
        sa.Column("hard_deadline", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(_in_clause("status", PROJECT_STATUSES), name="ck_projects_status"),
    )

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("project_id", sa.Integer, sa.ForeignKey("projects.id", ondelete="SET NULL")),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("owner_id", sa.Integer, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("delegator_id", sa.Integer, sa.ForeignKey("users.id", ondelete="SET NULL")),
        sa.Column("est_minutes", sa.Integer, nullable=False, server_default="25"),
        sa.Column("priority_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("importance", sa.Integer, nullable=False, server_default="5"),
        sa.Column("momentum_weight", sa.Float, nullable=False, server_default="0"),
        sa.Column("deadline", sa.DateTime(timezone=True)),
        sa.Column("status", sa.String(32), nullable=False, server_default="pending"),
        sa.Column("is_immutable", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.CheckConstraint(_in_clause("status", TASK_STATUSES), name="ck_tasks_status"),
        sa.CheckConstraint("importance >= 1 AND importance <= 10", name="ck_tasks_importance_range"),
        sa.CheckConstraint("est_minutes > 0", name="ck_tasks_est_positive"),
    )
    op.create_index("ix_tasks_status_priority", "tasks", ["status", "priority_score"])
    op.create_index("ix_tasks_deadline", "tasks", ["deadline"])
    op.create_index("ix_tasks_owner_status", "tasks", ["owner_id", "status"])

    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.Integer, sa.ForeignKey("tasks.id", ondelete="CASCADE"), primary_key=True),
        sa.Column(
            "depends_on_task_id",
            sa.Integer,
            sa.ForeignKey("tasks.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.CheckConstraint("task_id <> depends_on_task_id", name="ck_taskdep_no_self_edge"),
    )

    op.create_table(
        "delegation_graph",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("parent_user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="SET NULL")),
        sa.Column("materialized_path", sa.String(512), nullable=False),
        sa.Column("depth", sa.Integer, nullable=False, server_default="0"),
        sa.UniqueConstraint("user_id", name="uq_delegation_graph_user"),
    )
    # Generic index for SQLite + Postgres parity; on Postgres, also add a
    # text_pattern_ops variant so LIKE 'parent/%' subtree queries hit the index.
    op.create_index("ix_delegation_graph_path", "delegation_graph", ["materialized_path"])
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.create_index(
            "ix_delegation_graph_path_textops",
            "delegation_graph",
            ["materialized_path"],
            postgresql_ops={"materialized_path": "text_pattern_ops"},
        )

    op.create_table(
        "calendar_blocks",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("task_id", sa.Integer, sa.ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False),
        sa.Column("gcal_event_id", sa.String(255), unique=True),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('start < "end"', name="ck_calendar_block_time_order"),
    )
    op.create_index("ix_calendar_blocks_task", "calendar_blocks", ["task_id"])
    op.create_index("ix_calendar_blocks_start", "calendar_blocks", ["start"])

    op.create_table(
        "gamification_state",
        sa.Column(
            "user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
        ),
        sa.Column("points", sa.Integer, nullable=False, server_default="0"),
        sa.Column("current_streak", sa.Integer, nullable=False, server_default="0"),
        sa.Column("longest_streak", sa.Integer, nullable=False, server_default="0"),
        sa.Column("last_action_at", sa.DateTime(timezone=True)),
        sa.Column("unlocked_themes", sa.JSON),
    )

    op.create_table(
        "presence",
        sa.Column(
            "user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
        ),
        sa.Column("status", sa.String(32), nullable=False, server_default="offline"),
        sa.Column("current_task_id", sa.Integer, sa.ForeignKey("tasks.id", ondelete="SET NULL")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(_in_clause("status", PRESENCE_STATUSES), name="ck_presence_status"),
    )

    op.create_table(
        "execution_log",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("task_id", sa.Integer, sa.ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("estimated_minutes", sa.Integer, nullable=False),
        sa.Column("actual_minutes", sa.Integer, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_execution_log_user", "execution_log", ["user_id"])
    op.create_index("ix_execution_log_task", "execution_log", ["task_id"])


def downgrade() -> None:
    op.drop_index("ix_execution_log_task", table_name="execution_log")
    op.drop_index("ix_execution_log_user", table_name="execution_log")
    op.drop_table("execution_log")
    op.drop_table("presence")
    op.drop_table("gamification_state")
    op.drop_index("ix_calendar_blocks_start", table_name="calendar_blocks")
    op.drop_index("ix_calendar_blocks_task", table_name="calendar_blocks")
    op.drop_table("calendar_blocks")
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.drop_index("ix_delegation_graph_path_textops", table_name="delegation_graph")
    op.drop_index("ix_delegation_graph_path", table_name="delegation_graph")
    op.drop_table("delegation_graph")
    op.drop_table("task_dependencies")
    op.drop_index("ix_tasks_owner_status", table_name="tasks")
    op.drop_index("ix_tasks_deadline", table_name="tasks")
    op.drop_index("ix_tasks_status_priority", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("projects")
    op.drop_table("users")
